version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
      - ./client/dist:/usr/share/nginx/html
    depends_on:
      - server
      - client
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - VITE_BACKEND_URL=https://api.${ROOT_DOMAIN}
      - VITE_ROOT_DOMAIN=${ROOT_DOMAIN}
    volumes:
      - ./client:/app
      - /app/node_modules
    networks:
      - app-network

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - ROOT_DOMAIN=${ROOT_DOMAIN}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
